### ISSUE TITLE
Compatibility with iron-router

### ISSUE THREAD

**Issue by cbwheadon** [yasinuslu/blaze-meta#11]
This package looks great - but does it work with different meta-data for different routes under iron-router?

**Comment by johanbrook** [comment]
@cbwheadon I wrote this package for that: https://atmospherejs.com/lookback/seo, which uses `blaze-meta` under the hood. Give it a spin.

**Comment by yasinuslu** [comment]
@johanbrook Your package looks great i was thinking of adding iron-router integration, i'll mention this in readme.

**Comment by johanbrook** [comment]
Cool, thanks! I was about to build the meta tag rendering myself when I stumbled upon this neat package. Great job.
