### ISSUE TITLE
setTitle, iron:router and Browser History

### ISSUE THREAD

**Issue by marceloschmidt** [yasinuslu/blaze-meta#13]
If you are using iron:router and set page title based on route, browser history gets all messed up. I've tried Meta.setTitle in onBeforeAction, onAfterAction and action. 

For testing, add three routes and on each route set a different title. Then, on your application, move from one route to another then to another. Then check the titles under history by clicking and holding the back button on your browser (assuming you are using Chrome).

**Comment by themeteorchef** [comment]
Can confirm this, too. In my case it actually seems to break the router altogether until I refresh the page. 

@yasinuslu Any thoughts on how to fix?

**Comment by yasinuslu** [comment]
I had some problems with iron-router i fixed them with ec49b4f98dd1490c64b7ed3aa35f9c17e79e8393 
Do you guys still have this problem ?
