### ISSUE TITLE
blaze-meta config not setting properly

### ISSUE THREAD

**Issue by aadamsx** [yasinuslu/blaze-meta#22]
I have the following code running in the /client directory, it doesn't set the company every time:
```
Tracker.autorun(function () {
  var config = Meteor.subscribe('public_configuration');
  if (config.ready()) {

    var company = configurations.findOne({ configuration_type: 'public' });
    console.log('meta config | company: ', company);

    if (company && company.company_name) {
      // Gets you 'Company Name' as a default title not 'Default Title'
      console.log('meta config | company name: ', company.company_name);
      Meta.config({
        options: {
          title: company.company_name,
          suffix: company.company_name
        }
      });
    }
  }
});
```

I get this from the Chrome console, so I know it's picking up company name and running the code:

```
meta config | company:  Object
meta-tracker.js:33 meta config | company name:  Test Inc.
```

On initial load it will not set, then if I refresh the page the company name will get set properly.  Then if I hit refresh again, it will revert back to localhost:3000.  On other times it says with the company name.  And this is on my local box.

When I deploy to staging, I can never get the tab title to change with the same code.

It must be a timing issue? 

What am I doing wrong?

**Comment by yasinuslu** [comment]
Meta.config isn't reactive so probably it gets called after the initialization
```js
 config: function(opts) {
    _.extend(Meta.options, opts.options);
    _.extend(Meta.converters, opts.converters);
  },
```

Here is the inializing code:
```js
Meteor.startup(function() {
  Meta.init();

  Blaze.render(Template.MetaTags, document.head);

  Tracker.autorun(function() {
    document.title = Meta.getTitle();
  });
});
```

This might trigger an update if you put this after calling Meta.config
```js
Meta.dict.keyDeps.title.changed();
```

**Comment by aadamsx** [comment]
The call to the dict after calling ```Meta.config``` did work.  The only thing that does work is calling ```Meta.setTitle(company.company_name);``` after the call to ```Meta.config```.  I guess by doing this I don't even need the call to ```Meta.config```.

Thanks.

**Comment by yasinuslu** [comment]
I'm glad it's working, i'm closing this.
