### ISSUE TITLE
Unsetting all meta tags

### ISSUE THREAD

**Issue by blaind** [yasinuslu/blaze-meta#23]
I'm using angular-meteor with ui-router, hence og:tags stay after set and a new page is opened. For now, I've solved this as such:

      $rootScope.$on('$stateChangeStart', function(event, toState, toParams, fromState, fromParams) {
        _.each(Meta.arr(), function(item) {
          Meta.unset(item.property);
        });
      });

would be nice to have a Meta.unsetAll(); method so that _.each loop could be ommitted.

**Comment by yasinuslu** [comment]
Done with 6f49f7f , i forgot to mention this issue :)

**Comment by blaind** [comment]
Thank you! :)
